#! /bin/bash -u

make all

echo sequential no GUI
java NBody 1 50 10 10000

echo sequential with GUI
java NBody 1 50 10 10000 true
echo \n
for value in {1..32}
do
	echo parallel $value no GUI
	java NBodyParallel $value 50 10 10000
	echo parallel $value with GUI
	java NBodyParallel $value 50 10 10000 true
	echo \n
done
